server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    #设置数据库环境
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?serverTimezone=GMT%2B8
    username: root
    password: yyx20021215
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    #表示是否将自己注册进入Eureka Server，默认为true
    register-with-eureka: true
    #是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
mybatis-plus:
  configuration:
    #mybatis-plus日志设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
